"""ex33_05 ver2

Revision ID: 3e546410fe79
Revises:
Create Date: 2026-03-12 19:29:47.442075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e546410fe79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemex05',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_itemdb_name'), table_name='itemdb')
    op.drop_table('itemdb')
    op.drop_index(op.f('ix_itemindb_name'), table_name='itemindb')
    op.drop_table('itemindb')
    op.drop_index(op.f('ix_itemex04_name'), table_name='itemex04')
    op.drop_table('itemex04')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemex04',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('itemex04_pkey'))
    )
    op.create_index(op.f('ix_itemex04_name'), 'itemex04', ['name'], unique=False)
    op.create_table('itemindb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('itemindb_pkey'))
    )
    op.create_index(op.f('ix_itemindb_name'), 'itemindb', ['name'], unique=False)
    op.create_table('itemdb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('itemdb_pkey'))
    )
    op.create_index(op.f('ix_itemdb_name'), 'itemdb', ['name'], unique=False)
    op.drop_table('itemex05')
    # ### end Alembic commands ###
