services:

  api:
    build: .  # このディレクトリのdockerfileを使ってビルド
    ports:
      - "8000:8000" # ホストコンテナのポートマッピング
    environment:
      DATABASE_URL: postgresql://kimera:secret@db:5432/ex34
    depends_on:
      - db  # dbコンテナが起動してからapiを起動する
    volumes:
      - ./alembic:/app/alembic
      # ローカルからファイルをいじるためにマウント
      # この場合は、履歴ファイルへの追記のために利用

  db:
    image: postgres:15  # DBコンテナの
    environment:
      POSTGRES_USER: kimera
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ex34
    ports:
      -"5433:5432"
      # ローカルの5432ポートはpostgreが専有しているので、5433を指定
