name: CI
on: [push]

# ワークフローで処理するジョブを指定「test」
jobs:
  test:
    runs-on: ubuntu-latest  # ジョブの動作OSを指定

    # ジョブで順番に処理するリスト
    steps:
      - uses: actions/checkout@v4
      # gitリポジトリからコードを仮想環境にクローンしてくる

      - name: Set up Python # ステップの表示名
        uses: actions/setup-python@v5 # 指定のpythonを仮想環境にセットアップ
        with:
          python-version: "3.11"  # アクションの引数、versionを指定

      # 依存関係の仮想環境へのインストールをシェルで実行
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -v
